### ISSUE TITLE
After updating to the latest release i.e (1.29.4), I am getting a syntax error from one of the dependencies of rainbow-node-sdk

### ISSUE THREAD

**Issue by suhaibjanjua** [Rainbow-CPaaS/Rainbow-Node-SDK#2]
```
/home/root/messenger/node_modules/@xmpp/client/index.js:4
const {xml, jid} = require('@xmpp/client-core')
      ^

SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/ubuntu/AdamWithRainbow/node_modules/rainbow-node-sdk/lib/connection/XMPPService.js:13:14)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
```

**Comment by suhaibjanjua** [comment]
I have updated my Node.JS version to 6.11.1 LTS. And now everything working smoothly.

**Comment by suhaibjanjua** [comment]
I have updated my Node.JS version to 6.11.1 LTS. And now everything is working smoothly.
